[tool.poetry]
name = "writefreely-to-markdown"
version = "0.1.0"
description = ""
authors = ["Ryan <ryan@alien.gov>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
tomlkit = "^0.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
